#!/usr/bin/env python3
"""Smoke test for Repro-It tools against demo_repo."""

import sys
import os
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from tools import read_file, search_repo, write_test, run_pytest


def main():
    """Run smoke tests on tools using demo_repo."""
    
    # Get paths
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    demo_repo = repo_root / "demo_repo"
    
    print("🔧 Repro-It Tools Smoke Test")
    print("=" * 50)
    
    # Test 1: Read file
    print("\n1. Testing read_file...")
    result = read_file(str(demo_repo / "pricing.py"), str(demo_repo))
    if result["ok"] and "calculate_total" in result["content"]:
        print("   ✓ read_file works")
    else:
        print(f"   ✗ read_file failed: {result['error']}")
        return 1
    
    # Test 2: Search repo
    print("\n2. Testing search_repo...")
    result = search_repo("calculate_discount", str(demo_repo))
    if result["ok"] and len(result["matches"]) > 0:
        print(f"   ✓ search_repo found {len(result['matches'])} matches")
    else:
        print(f"   ✗ search_repo failed: {result['error']}")
        return 1
    
    # Test 3: Write test
    print("\n3. Testing write_test...")
    test_code = '''"""Smoke test generated by tool."""

def test_smoke():
    """Basic smoke test."""
    assert 1 + 1 == 2
'''
    result = write_test("tests/test_smoke_generated.py", test_code, str(demo_repo))
    if result["ok"]:
        print(f"   ✓ write_test created: {result['path']}")
        test_file_path = result["path"]
    else:
        print(f"   ✗ write_test failed: {result['error']}")
        return 1
    
    # Test 4: Run pytest
    print("\n4. Testing run_pytest...")
    result = run_pytest("tests/test_smoke_generated.py", str(demo_repo))
    if result["ok"] and result["exit_code"] == 0:
        print("   ✓ run_pytest executed successfully")
    else:
        print(f"   ✗ run_pytest failed: {result['error']}")
        if result["failure_messages"]:
            print(f"   Failures: {result['failure_messages']}")
        return 1
    
    # Cleanup
    print("\n5. Cleaning up...")
    if Path(test_file_path).exists():
        Path(test_file_path).unlink()
        print("   ✓ Removed test file")
    
    print("\n" + "=" * 50)
    print("✅ All smoke tests passed!")
    return 0


if __name__ == "__main__":
    sys.exit(main())

# Made with Bob
